#!/usr/bin/bash

tag=$(git rev-parse --short HEAD)

# 0 : 0:03
# 1 : 0:02
# 2 : ~5 min
# 3 : 1:51
# 4 : 2:45
# 5 : 2:48
# 6 : 3:15
# 7 : 1:38
# 8 : 0:29
# 9 : 0:03
# 10: 0:00
# 11: 0:01
# 12: 0:22
# 13: 0:02
# 14: 1:30
# 15: 0:02
# 16: 0:08
# 17: 0:01
# 18: 0:05
# 19: 0:01
# 20: 0:05
# 21: 0:00
# 22: 0:01
# 23: 0:00
# 24: 16:18

fast="0 1 8 9 10 11 12 13 15 16 17 18 19 20 21 22 23"
med="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23"

#for i in $(seq 0 23); do
cp play_icfp2015 submissions/play.$tag
for i in $med; do
  json=submissions/p.$i.$tag.json
  echo "Solving $i to $json"
  test -f $json && printf "File $json already exists"
  test -f $json && exit 200
  cmd="./submissions/play.$tag  $(cat words) -f ../problems/problem_$i.json --tag $tag"
  #echo $cmd
  eval $cmd > $json
  ./push-solution $json
done
